Add automated tests for the dotfiles
Add an automated testing to verify that the dotfiles can install and
work properly, currently only with Linux.

diff --git a/home/.chezmoiscripts/run_onchange_before_brew-install.sh.tmpl b/home/.chezmoiscripts/run_onchange_before_brew-install.sh.tmpl
--- a/home/.chezmoiscripts/run_onchange_before_brew-install.sh.tmpl
+++ b/home/.chezmoiscripts/run_onchange_before_brew-install.sh.tmpl
@@ -1,6 +1,15 @@
 #!/usr/bin/env bash
 
-set -eufo pipefail
+# Exit on error. Append || true if you expect an error.
+set -o errexit
+# Exit on error inside any functions or subshells.
+set -o errtrace
+# Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
+set -o nounset
+# Catch the error in case mysqldump fails (but gzip succeeds) in `mysqldump |gzip`
+set -o pipefail
+# Turn on traces, useful while debugging but commented out by default
+#set -o xtrace
 
 if [[ -e $HOME/dev/brew/bin ]]; then
   export PATH="$HOME/dev/brew/bin:$PATH"
@@ -39,7 +48,7 @@ fi
      "mysql-client"
      "vault"
 }}
-
+# TODO need to install gcc@5 on linux for Go to work... Does it work with
 {{ $casks := list -}}
 {{ $taps := list -}}
 {{ $mases := dict -}}
